spring-cloud/spring-cloud-dataflow-server-cloudfoundry

src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/ApplicationModuleDeployer.java
Fixes spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#12
=> Adding quotes around option values containing spaces

spring-cloud-dataflow-admin-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/ApplicationModuleDeployer.java
Fixes spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#36
=> Wrap arguments inside quotes to protect against eval

spring-cloud-dataflow-deployer-cloudfoundry/pom.xml
Fixes spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#54
=> Use correct parent pom location

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
Update documentation after changes to CF ConfigurationProperty names in https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/28
=> Update to new deployer CF properties

spring-cloud-dataflow-server-cloudfoundry/src/main/resources/dataflow-server.yml
Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry#111
=> Disable tasks support on CF for now

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/index.adoc
- Also fix getting started header
=> Include architecture doc

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
- change all env-var's from upper -> lower
- add `config-server` instruction
- fix previously committed formatting issue .. see below
=> Update env-var's from upper to lower case

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-dataflow-server-cloudfoundry/src/main/resources/dataflow-server.yml
=> Add experimental flag to enabling tasks property

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry#159
Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry#138
=> Document stream/task split Clarify usage of each service Formatting fixes

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-dataflow-server-cloudfoundry/src/main/resources/dataflow-server.yml
Fix doco related to tasks toggle
Clean application.yml
=> Fix default for tasks to be DISABLED

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry#165
=> Fix docs following stream/task split

spring-cloud-dataflow-server-cloudfoundry-docs/pom.xml, spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/index.adoc
Some general cleanup of properties
Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/181
=> Make sure the proper branch / tag of docs is being used from github.

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-dataflow-server-cloudfoundry/src/main/resources/dataflow-server.yml
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/189
=> Document task launch timeout

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
http://bit.ly/stream-applications-rabbit-maven points 1.0.0-SNAPSHOT
=> Import stable apps

pom.xml, spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/index.adoc
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/200
=> [Merge once SCDF M2 is released] Include new doc section. Depend on newest SCDF version

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
=> Update to recommend 2G for server in getting started

spring-cloud-dataflow-server-cloudfoundry/pom.xml
- should be "Cloud Foundry Data Flow Server"
=> Fix server project name

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/cf-tasks.adoc
=> Added instructions on deleting tasks from PCF

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
=> Tidy up disk usage documentation

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/248
=> Document custom route via deployment properties

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/overview.adoc
- rephrase scdf introduction
- add task doc links
- format doc sections
=> Remove experimental reference to Task

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
1) remove unnecessary config-server configuration section 
2) fix bit.ly link
=> Remove cf-server + config-server explicit integration steps

spring-cloud-dataflow-server-cloudfoundry/pom.xml
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/290
=> Add git-commit-id-plugin

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/294
=> Document setting task properties in Docker context

pom.xml
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/309
=> Depend on SCDF 1.2.RC1

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/index.adoc
Clarify maven configuration. Remove auth and proxy config which is confusing in this context and add a NOTE with a link to the SCDF maven configuration.
=> Fix maven configuration

pom.xml, spring-cloud-dataflow-server-cloudfoundry-autoconfig/src/main/java/org/springframework/cloud/dataflow/server/cloudfoundry/config/CloudFoundryServerConfigurationProperties.java, spring-cloud-dataflow-server-cloudfoundry/src/test/java/org/springframework/cloud/dataflow/server/cloudfoundry/CloudFoundryDataFlowServerApplicationTests.java, src/checkstyle/checkstyle-header.txt, src/checkstyle/checkstyle.xml, src/eclipse/eclipse-code-formatter.xml, src/eclipse/eclipse.importorder
=> Adapting to new checkstyle and code formatting rules

spring-cloud-dataflow-server-cloudfoundry-autoconfig/src/main/java/org/springframework/cloud/dataflow/server/cloudfoundry/config/security/CloudFoundryOAuthSecurityConfiguration.java, spring-cloud-dataflow-server-cloudfoundry-autoconfig/src/main/java/org/springframework/cloud/dataflow/server/cloudfoundry/config/security/support/CloudFoundryPrincipalExtractor.java
* Add Cloud Foundry specific `PrincipalExtractor`
resolves https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/334
=> gh-334 In CF - Display the Username not the User Id

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
- Add a new section with the options described along with references
- Update broken links
=> List alternative options to resolve applications

pom.xml, spring-cloud-dataflow-server-cloudfoundry-autoconfig/pom.xml, spring-cloud-dataflow-server-cloudfoundry-autoconfig/src/main/java/org/springframework/cloud/dataflow/server/cloudfoundry/config/security/CloudFoundryOAuthSecurityConfiguration.java, spring-cloud-dataflow-server-cloudfoundry-autoconfig/src/main/java/org/springframework/cloud/dataflow/server/cloudfoundry/config/security/support/CloudFoundryDataflowAuthoritiesExtractor.java
- change scdf-core to `1.3.0.BUILD-SNAPSHOT`
- add the common security project as a dependency
- fix the imports/references
Though the tests pass, I couldn't verify the security integration successfully. It is tracked via spring-cloud/spring-cloud-dataflow-ui#455.
=> Bring master up to speed with 1.3.BS of SCDF-core

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/configuration.adoc
Resolves spring-cloud/spring-cloud-dataflow-server-cloudfoundry#356
=> Fix SAJ formatting issues in sample manifest.yml

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/streams-skipper.adoc
- Adapt to upstream's new command additions
- Add rollback section
=> Update stream-skipper docs

pom.xml
Resolves spring-cloud/spring-cloud-dataflow-server-cloudfoundry#376
=> Flip SCDF-core back to snapshots

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/configuration.adoc, spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/getting-started.adoc
resolves https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/381
=> gh-381 Fix broken security links in the reference guide

spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/configuration.adoc, spring-cloud-dataflow-server-cloudfoundry-docs/src/main/asciidoc/index.adoc
=> Added DSL deployment properties section

pom.xml, spring-cloud-dataflow-server-cloudfoundry/pom.xml
Fixes #403
Update to
* deployer 1.3.2.RELEASE
* deployer-cf 1.4.0.M1
* skipper 1.0.2 (just for docs)
* boot 1.5.12
=> Update deployer-spi/deployer-cf/boot deps

pom.xml, spring-cloud-dataflow-server-cloudfoundry/pom.xml
resolves #418
Updated to latest release of CF server
=> Updated dependencies to include Scheduler
